import Picture from '@/component/common/shared/Picture';
import DefaultLayout from '@/component/layouts/DefaultLayout';
import Head from 'next/head';
import { ReactElement } from 'react';

const PageNotFound = () => {
	return (
		<>
			<Head>
				<title>404 - Page not found</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<section id="page-not-found" className="bg-[#F8F9FA] py-20">
				<div className="container mx-auto">
					<div className="flex items-center justify-center flex-col gap-6">
						<Picture
							link={'/assets/404.png'}
							classList={'w-[354px] h-[184px]'}
							alt={'404 not found'}
						/>
						<h5 className="text-[#303344] font-medium text-lg">
							ERROR 404
						</h5>
						<p className="text-[#000000] text-base font-normal w-[450px] text-center">
							Sorry we can’t find what you are looking for, here’s
							some{' '}
							<span className="underline">suggested topics</span>{' '}
							for you.
						</p>
					</div>
				</div>
			</section>
		</>
	);
};
PageNotFound.getLayout = function getLayout(page: ReactElement) {
	return <DefaultLayout>{page}</DefaultLayout>;
};
export default PageNotFound;
