import AdminAuthLayout from '@/component/layouts/AdminAuthLayout';
import { ReactElement, useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import AdminPageTitle from '../../component/common/admin/AdminPageTitle';
import dynamic from 'next/dynamic';
import { BiPlus } from 'react-icons/bi';
import Head from 'next/head';
import { useFetchData } from '@/hooks/useApi';
import Link from 'next/link';
import CustomPagination from '@/component/common/shared/CustomPagination';
import Spinner from '@/component/common/shared/Spinner';
const CategoryForm = dynamic(
	() => import('@/component/common/admin/CategoryForm'),
	{
		ssr: false,
	},
);

type CategoryType = {
	createdAt: Date;
	threads: string[];
	title: string;
	_id: string;
	background: string;
};

const Categories = () => {
	const [show, setShow] = useState(false);
	const [page, setPage] = useState(1);
	const { data: categories, isLoading } = useFetchData(
		`/api/category/all?select=title,threads,createdAt,_id,background&limit=6&page=${page}`,
		['categories'],
		page,
	);

	return (
		<>
			<Head>
				<title>Thread categories</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			{isLoading ? (
				<Spinner />
			) : categories.status === 'success' ? (
				<section id="categories">
					<div className="flex items-center justify-between mb-3">
						<div>
							<AdminPageTitle
								title={'Categories'}
								subtitle={'Admin / Categories'}
							/>
						</div>
						<button
							className="bg-[#2171cd] h-12 w-12 flex items-center justify-center rounded-full group"
							onClick={() => setShow(!show)}
						>
							<BiPlus className="text-3xl text-white duration-300 group-hover:rotate-[360deg]" />
						</button>
					</div>
					{categories.data.length > 0 ? (
						<div className="categories-list-wrapper">
							<div className="categories-list mt-6">
								<div className="category-card-wrapper">
									<div className="category-items-header grid grid-cols-9 px-6 py-5 bg-white">
										<h5 className="col-span-4 text-[#303344] font-medium text-base">
											category
										</h5>
										<h5 className="text-[#303344] font-medium text-base text-center">
											Join date
										</h5>
										<h5 className="text-[#303344] font-medium text-base text-center">
											Last Activity
										</h5>
										<h5 className="text-[#303344] font-medium text-base text-center">
											Threads
										</h5>
										<h5 className="text-[#303344] font-medium text-base text-center">
											Replies
										</h5>
										<h5 className="text-[#303344] font-medium text-base text-center">
											Action
										</h5>
									</div>

									{categories.data.map(
										(item: CategoryType, index: number) => (
											<div
												className="category-item"
												key={index}
											>
												<div className="thread-card grid grid-cols-9 gap-4 bg-[#f1f3f5] py-5 px-6 border-b border-b-[#e1e7e9]">
													<div className="category flex items-center col-span-4 gap-4">
														<span
															className="text-white text-sm font-normal py-1 px-2 rounded-[4px]"
															style={{
																backgroundColor:
																	item.background,
															}}
														>
															{item.title}
														</span>
													</div>

													<div className="flex items-center justify-center">
														{new Date(
															item.createdAt,
														).toLocaleString(
															'en-US',
															{
																timeZone: 'UTC',
																weekday:
																	'short',
																year: '2-digit',
																month: 'short',
																day: 'numeric',
															},
														)}
													</div>
													<h5 className="flex items-center justify-center text-base text-[#666f74] font-normal">
														2 hours ago
													</h5>
													<h5 className="flex items-center justify-center text-base text-[#182730] font-medium">
														3
													</h5>
													<h5 className="flex items-center justify-center text-base text-[#666f74] font-normal">
														29
													</h5>
													<h5 className="flex items-center justify-center text-base text-[#666f74] font-normal">
														1d
													</h5>
												</div>
											</div>
										),
									)}
								</div>
							</div>
							<div className="mt-6">
								<CustomPagination
									currentpage={categories.currentPage}
									totalPage={categories.pages}
									handler={setPage}
								/>
							</div>
						</div>
					) : (
						<h4>Empty</h4>
					)}
				</section>
			) : (
				<h4>Empty</h4>
			)}

			<CategoryForm show={show} setShow={setShow} />
		</>
	);
};
Categories.getLayout = function getLayout(page: ReactElement) {
	return <AdminAuthLayout>{page}</AdminAuthLayout>;
};
export default Categories;
