import AdminPageTitle from '@/component/common/admin/AdminPageTitle';
import AdminThread from '@/component/common/admin/AdminThread';
import CustomPagination from '@/component/common/shared/CustomPagination';
import AdminAuthLayout from '@/component/layouts/AdminAuthLayout';
import { useFetchData } from '@/hooks/useApi';
import { Spinner } from 'flowbite-react';
import Head from 'next/head';
import React, { ReactElement } from 'react';
import { useState } from 'react';

const Threads = () => {
	const [page, setPage] = useState(1);
	const { data: thread, isLoading } = useFetchData(
		`/api/dashboard/threads?limit=5&page=${page}`,
		['admin-thread'],
		page,
	);

	return (
		<>
			<Head>
				<title>Thread list</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			{isLoading ? (
				<div className="flex items-center gap-3">
					<Spinner color="info" className="!text-[#0e0e2354]" />
					<span>Loading...</span>
				</div>
			) : thread.status === 'success' ? (
				<section id="threads">
					<div className="mb-6">
						<AdminPageTitle
							title={'Threads'}
							subtitle={'Admin / Threads'}
						/>
					</div>

					<div className="threads-list mt-6">
						{thread.data.length > 0 ? (
							<>
								<AdminThread thread={thread.data} />
								<div className="mt-6">
									<CustomPagination
										currentpage={thread.currentPage}
										totalPage={thread.pages}
										handler={setPage}
									/>
								</div>
							</>
						) : (
							<h2 className="text-xl font-medium capitalize pt-10">
								No Thread Found...
							</h2>
						)}
					</div>
				</section>
			) : (
				<h2 className="text-xl">No Thread Found...</h2>
			)}
		</>
	);
};
Threads.getLayout = function getLayout(page: ReactElement) {
	return <AdminAuthLayout>{page}</AdminAuthLayout>;
};
export default Threads;
